places = ['Korea', 'Japan', 'United State', 'Saudi Arabia', 'New Zealand']
print(f'original:{places}')
print(f'ordered:{sorted(places)}')
print(f'ordered reverse:{sorted(places, reverse=True)}')
print(f'original:{places}')
places.reverse()
print(f'reverse:{places}')
places.reverse()
print(f'reverse the reverse:{places}')
places.sort()
print(f'sort:{places}')
places.sort(reverse=True)
print(f'sort reverse:{places}')
print(f'size:{len(places)}')